### PR TITLE
Add book links for all Practical AI episodes

### PR DESCRIPTION
**Pull request by jasonkeene**
This change adds a books section to each Practical AI episode that had a book mentioned in the transcripts. The book link format for existing books was updated to be more consistent. I also made some trivial changes to whitespace for consistency which is why the diff is so noisy.

Merry Christmas! 🎄🎁

### CODE REVIEW

**Comment by jerodsanto** [comment]
Wow, these changes are extensive! Did you do it manually or was there some coding involved?

Also, is there any chance we could have it sans whitespace changes? It's very hard to see what all is going on here, which makes me hesitant to merge for now...

**Comment by jasonkeene** [comment]
Yea, I can revert the whitespace changes. I generated these changes off a JSON file I created by grepping through the transcripts and doing a bit of manual research. I'm looking to spend some money on books before EoY and figured I'd data mine the transcripts for book recommendations.

**Comment by jasonkeene** [comment]
Ok, I force pushed and remove the whitespace changes to minimize the diff.

**Comment by jasonkeene** [comment]
Some comments about the diff:

- Some of the links I updated to the newer editions to not send people to old versions.
- Some book titles changed after the podcast was released but before the book was published.
- I used amazon for most links but where there was a link already in the notes I used that.
- All amazon links use the short URL vs one with the title in the URL for brevity.
- Some links were broken or old so I updated them.
- For most titles I dropped the subtitle for brevity.

**Comment by jerodsanto** [comment]
We appreciate the effort, @jasonkeene! 💚💚💚

@all-contributors please add @jasonkeene for doc

**Pull request merged**
