### PR TITLE
Add: New Link

### PR DESCRIPTION
**Pull request by shubhneet182**
Link to clear confusion b/w AI, ML and deep learning.

### CODE REVIEW

**Comment by jerodsanto** [comment]
@shubhneet182 was that link referenced on the show?

**Comment by shubhneet182** [comment]
Hi,

I don't know about that. I just sent a pull request to add this link as
people are often confused between AI, ML and DL.

Sorry if it's not of relevance to you as I have not been fully able to
understand how to contribute to your repo as I am a beginner.

Thanks
Shubhneet Sandhu

**Comment by jerodsanto** [comment]
We appreciate your effort!

This repo contains the show notes for our podcast episodes. The one you edited is episode [#1 of Practical AI](https://changelog.com/practicalai/1).

The idea behind show notes is they are links, notes, etc. of these referenced on the podcast that people can use to follow-up on interesting things they heard while listening.

The _best_ way to contribute to this repo is to listen to the shows and if you hear things referenced in the conversation that are *not* in the show notes, add them! OR if you see broken links and spelling errors in the show notes, fix them.

I hope that helps 💚

**Comment by shubhneet182** [comment]
Thanks! It's really helpful.

**Comment by jerodsanto** [comment]
Looking forward to future pulls 😀

**Pull request closed without merging**
